[project]
name = "snapshot-virtual-machine"
authors = ["Snapshot VM Team"]
description = "A decentralized asset management protocol on Stacks"
telemetry = false
requirements = []
[contracts.snapshot-vm]
path = "contracts/snapshot-vm.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
